export const books = [
    {
        "id": 1,
        "book_id": "recIFusdNl6d8dj3L",
        "book_number": 1,
        "osis_name": "Gen",
        "label": "Genesis",
        "testament": "Old Testament",
        "book_group": "Pentateuch",
        "chapter_count": "50",
        "verse_count": "1533",
        "writers": "[\"moses_2108\"]",
        "slug": "gen",
        "people_count": "1082",
        "place_count": "266",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:21:49",
        "summary": null,
        "short_name": "Ge"
    },
    {
        "id": 2,
        "book_id": "recsr5TGvFGOwA5SZ",
        "book_number": 2,
        "osis_name": "Exod",
        "label": "Exodus",
        "testament": "Old Testament",
        "book_group": "Pentateuch",
        "chapter_count": "40",
        "verse_count": "1213",
        "writers": "[\"moses_2108\"]",
        "slug": "exod",
        "people_count": "619",
        "place_count": "179",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:30:01",
        "summary": null,
        "short_name": "Ex"
    },
    {
        "id": 3,
        "book_id": "rec6qL6gTvX4tUw4A",
        "book_number": 3,
        "osis_name": "Lev",
        "label": "Leviticus",
        "testament": "Old Testament",
        "book_group": "Pentateuch",
        "chapter_count": "27",
        "verse_count": "859",
        "writers": "[\"moses_2108\"]",
        "slug": "lev",
        "people_count": "366",
        "place_count": "28",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:31:19",
        "summary": null,
        "short_name": "Le"
    },
    {
        "id": 4,
        "book_id": "recs5u7KfYwwEE6JO",
        "book_number": 4,
        "osis_name": "Num",
        "label": "Numbers",
        "testament": "Old Testament",
        "book_group": "Pentateuch",
        "chapter_count": "36",
        "verse_count": "1288",
        "writers": "[\"moses_2108\"]",
        "slug": "num",
        "people_count": "832",
        "place_count": "207",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:32:33",
        "summary": null,
        "short_name": "Nu"
    },
    {
        "id": 5,
        "book_id": "rec2LnZw7EoTWReC0",
        "book_number": 5,
        "osis_name": "Deut",
        "label": "Deuteronomy",
        "testament": "Old Testament",
        "book_group": "Pentateuch",
        "chapter_count": "34",
        "verse_count": "959",
        "writers": "[\"moses_2108\"]",
        "slug": "deut",
        "people_count": "528",
        "place_count": "146",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:34:00",
        "summary": null,
        "short_name": "Dt"
    },
    {
        "id": 6,
        "book_id": "rec5dSv8N1iv8z9uC",
        "book_number": 6,
        "osis_name": "Josh",
        "label": "Joshua",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "24",
        "verse_count": "658",
        "writers": "[\"joshua_1727\"]",
        "slug": "josh",
        "people_count": "413",
        "place_count": "370",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:36:01",
        "summary": null,
        "short_name": "Jos"
    },
    {
        "id": 7,
        "book_id": "reczL2ckRW1qHvVfe",
        "book_number": 7,
        "osis_name": "Judg",
        "label": "Judges",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "21",
        "verse_count": "618",
        "writers": "[\"samuel_2469\"]",
        "slug": "judg",
        "people_count": "454",
        "place_count": "244",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:37:17",
        "summary": null,
        "short_name": "Jdg"
    },
    {
        "id": 8,
        "book_id": "recZuCb9Bn0RErpsL",
        "book_number": 8,
        "osis_name": "Ruth",
        "label": "Ruth",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "4",
        "verse_count": "85",
        "writers": "[\"samuel_2469\"]",
        "slug": "ruth",
        "people_count": "57",
        "place_count": "9",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:38:26",
        "summary": null,
        "short_name": "Ru"
    },
    {
        "id": 9,
        "book_id": "rec4GS8yWh2R4mpdB",
        "book_number": 9,
        "osis_name": "1Sam",
        "label": "1 Samuel",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "31",
        "verse_count": "810",
        "writers": "[\"samuel_2469\", \"samuel_2469, gad_1263, nathan_2153\"]",
        "slug": "1sam",
        "people_count": "662",
        "place_count": "193",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:38:38",
        "summary": null,
        "short_name": "1Sa"
    },
    {
        "id": 10,
        "book_id": "recMYdxLC2GjLRomD",
        "book_number": 10,
        "osis_name": "2Sam",
        "label": "2 Samuel",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "24",
        "verse_count": "695",
        "writers": "[\"samuel_2469, gad_1263, nathan_2153\"]",
        "slug": "2sam",
        "people_count": "556",
        "place_count": "166",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:40:16",
        "summary": null,
        "short_name": "2Sa"
    },
    {
        "id": 11,
        "book_id": "reconzJEzr8kOsb3j",
        "book_number": 11,
        "osis_name": "1Kgs",
        "label": "1 Kings",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "22",
        "verse_count": "816",
        "writers": "[\"jeremiah_853\"]",
        "slug": "1kgs",
        "people_count": "586",
        "place_count": "192",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:41:45",
        "summary": null,
        "short_name": "1Ki"
    },
    {
        "id": 12,
        "book_id": "recutYqTqunXPJKQO",
        "book_number": 12,
        "osis_name": "2Kgs",
        "label": "2 Kings",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "25",
        "verse_count": "719",
        "writers": "[\"jeremiah_853\"]",
        "slug": "2kgs",
        "people_count": "554",
        "place_count": "265",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:43:47",
        "summary": null,
        "short_name": "2Ki"
    },
    {
        "id": 13,
        "book_id": "rec2ZFQHqI4eUjhqX",
        "book_number": 13,
        "osis_name": "1Chr",
        "label": "1 Chronicles",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "29",
        "verse_count": "942",
        "writers": "[\"ezra_1245\"]",
        "slug": "1chr",
        "people_count": "836",
        "place_count": "161",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:45:42",
        "summary": null,
        "short_name": "1Ch"
    },
    {
        "id": 14,
        "book_id": "rec410yOewjNfbeE3",
        "book_number": 14,
        "osis_name": "2Chr",
        "label": "2 Chronicles",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "36",
        "verse_count": "822",
        "writers": "[\"ezra_1245\"]",
        "slug": "2chr",
        "people_count": "611",
        "place_count": "236",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:47:14",
        "summary": null,
        "short_name": "2Ch"
    },
    {
        "id": 15,
        "book_id": "recit4Q50QB9nM3q2",
        "book_number": 15,
        "osis_name": "Ezra",
        "label": "Ezra",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "10",
        "verse_count": "280",
        "writers": "[\"ezra_1245\"]",
        "slug": "ezra",
        "people_count": "209",
        "place_count": "89",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:49:22",
        "summary": null,
        "short_name": "Ezr"
    },
    {
        "id": 16,
        "book_id": "rec3WEGPl0a1PS0cC",
        "book_number": 16,
        "osis_name": "Neh",
        "label": "Nehemiah",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "13",
        "verse_count": "406",
        "writers": "[\"nehemiah_2172\"]",
        "slug": "neh",
        "people_count": "259",
        "place_count": "99",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:50:02",
        "summary": null,
        "short_name": "Ne"
    },
    {
        "id": 17,
        "book_id": "rec6yHFZ6w7UUw5Cu",
        "book_number": 17,
        "osis_name": "Esth",
        "label": "Esther",
        "testament": "Old Testament",
        "book_group": "Historical",
        "chapter_count": "10",
        "verse_count": "167",
        "writers": "[\"mordecai_2107\"]",
        "slug": "esth",
        "people_count": "119",
        "place_count": "24",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:51:03",
        "summary": null,
        "short_name": "Es"
    },
    {
        "id": 18,
        "book_id": "recOA8nVVhKs30PSI",
        "book_number": 18,
        "osis_name": "Job",
        "label": "Job",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "42",
        "verse_count": "1070",
        "writers": "[\"moses_2108\"]",
        "slug": "job",
        "people_count": "190",
        "place_count": "6",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:51:27",
        "summary": null,
        "short_name": "Job"
    },
    {
        "id": 19,
        "book_id": "recKXZXO6cJwk2SxO",
        "book_number": 19,
        "osis_name": "Ps",
        "label": "Psalms",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "150",
        "verse_count": "2461",
        "writers": "[null, \"david_994\", \"asaph_330\", \"solomon_2762\", \"heman_1488\", \"ethan_1222\", \"moses_2108\"]",
        "slug": "ps",
        "people_count": "1026",
        "place_count": "118",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 20:54:46",
        "summary": null,
        "short_name": "Ps"
    },
    {
        "id": 20,
        "book_id": "recRLdYtz1vjdW7yd",
        "book_number": 20,
        "osis_name": "Prov",
        "label": "Proverbs",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "31",
        "verse_count": "915",
        "writers": "[\"solomon_2762\", \"agur_112\", \"lemuel_1817\"]",
        "slug": "prov",
        "people_count": "100",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 22:04:31",
        "summary": null,
        "short_name": "Pr"
    },
    {
        "id": 21,
        "book_id": "recd3p656hOWx95Jk",
        "book_number": 21,
        "osis_name": "Eccl",
        "label": "Ecclesiastes",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "12",
        "verse_count": "222",
        "writers": "[\"solomon_2762\"]",
        "slug": "eccl",
        "people_count": "37",
        "place_count": "5",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 22:08:26",
        "summary": null,
        "short_name": "Ec"
    },
    {
        "id": 22,
        "book_id": "recnUwcJABJVgZDCI",
        "book_number": 22,
        "osis_name": "Song",
        "label": "Song of Solomon",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "8",
        "verse_count": "117",
        "writers": "[\"solomon_2762\"]",
        "slug": "song",
        "people_count": "9",
        "place_count": "21",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 22:09:39",
        "summary": null,
        "short_name": "So"
    },
    {
        "id": 23,
        "book_id": "recr2ic6Ws3R14a5I",
        "book_number": 23,
        "osis_name": "Isa",
        "label": "Isaiah",
        "testament": "Old Testament",
        "book_group": "Major Prophets",
        "chapter_count": "66",
        "verse_count": "1292",
        "writers": "[\"isaiah_617\"]",
        "slug": "isa",
        "people_count": "556",
        "place_count": "248",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 22:10:31",
        "summary": null,
        "short_name": "Is"
    },
    {
        "id": 24,
        "book_id": "rec3jLxfw7hvvvw7J",
        "book_number": 24,
        "osis_name": "Jer",
        "label": "Jeremiah",
        "testament": "Old Testament",
        "book_group": "Major Prophets",
        "chapter_count": "52",
        "verse_count": "1364",
        "writers": "[\"jeremiah_853\"]",
        "slug": "jer",
        "people_count": "840",
        "place_count": "443",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-12 22:24:09",
        "summary": null,
        "short_name": "Je"
    },
    {
        "id": 25,
        "book_id": "recdT4VI6VdkEzixN",
        "book_number": 25,
        "osis_name": "Lam",
        "label": "Lamentations",
        "testament": "Old Testament",
        "book_group": "Poetry-Wisdom",
        "chapter_count": "5",
        "verse_count": "154",
        "writers": "[\"jeremiah_853\"]",
        "slug": "lam",
        "people_count": "47",
        "place_count": "22",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:36:43",
        "summary": null,
        "short_name": "La"
    },
    {
        "id": 26,
        "book_id": "recqSg3DygQ97p2n7",
        "book_number": 26,
        "osis_name": "Ezek",
        "label": "Ezekiel",
        "testament": "Old Testament",
        "book_group": "Major Prophets",
        "chapter_count": "48",
        "verse_count": "1273",
        "writers": "[\"ezekiel_1237\"]",
        "slug": "ezek",
        "people_count": "482",
        "place_count": "195",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:38:00",
        "summary": null,
        "short_name": "Eze"
    },
    {
        "id": 27,
        "book_id": "recJZDGEIEZOMQVFU",
        "book_number": 27,
        "osis_name": "Dan",
        "label": "Daniel",
        "testament": "Old Testament",
        "book_group": "Major Prophets",
        "chapter_count": "12",
        "verse_count": "357",
        "writers": "[\"daniel_975\"]",
        "slug": "dan",
        "people_count": "158",
        "place_count": "40",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:52:18",
        "summary": null,
        "short_name": "Da"
    },
    {
        "id": 28,
        "book_id": "rect9laYKg0Xd0Uzg",
        "book_number": 28,
        "osis_name": "Hos",
        "label": "Hosea",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "14",
        "verse_count": "197",
        "writers": "[\"hosea_1555\"]",
        "slug": "hos",
        "people_count": "95",
        "place_count": "44",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:55:32",
        "summary": null,
        "short_name": "Ho"
    },
    {
        "id": 29,
        "book_id": "recJhMBucEbOC6FyV",
        "book_number": 29,
        "osis_name": "Joel",
        "label": "Joel",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "3",
        "verse_count": "73",
        "writers": "[\"joel_1660\"]",
        "slug": "joel",
        "people_count": "31",
        "place_count": "16",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:57:35",
        "summary": null,
        "short_name": "Joe"
    },
    {
        "id": 30,
        "book_id": "rec5weNA8SDG9Gk1x",
        "book_number": 30,
        "osis_name": "Amos",
        "label": "Amos",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "9",
        "verse_count": "146",
        "writers": "[\"amos_238\"]",
        "slug": "amos",
        "people_count": "89",
        "place_count": "39",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:58:19",
        "summary": null,
        "short_name": "Am"
    },
    {
        "id": 31,
        "book_id": "recVlXpkRK0TkcxFm",
        "book_number": 31,
        "osis_name": "Obad",
        "label": "Obadiah",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "1",
        "verse_count": "21",
        "writers": "[\"obadiah_2226\"]",
        "slug": "obad",
        "people_count": "12",
        "place_count": "9",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 04:59:47",
        "summary": null,
        "short_name": "Ob"
    },
    {
        "id": 32,
        "book_id": "recHPjIgqDYfAbySY",
        "book_number": 32,
        "osis_name": "Jonah",
        "label": "Jonah",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "4",
        "verse_count": "48",
        "writers": "[\"jonah_1689\"]",
        "slug": "jonah",
        "people_count": "35",
        "place_count": "10",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:00:00",
        "summary": null,
        "short_name": "Jon"
    },
    {
        "id": 33,
        "book_id": "recA2CMdJWbqaoTA0",
        "book_number": 33,
        "osis_name": "Mic",
        "label": "Micah",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "7",
        "verse_count": "105",
        "writers": "[\"micah_2053\"]",
        "slug": "mic",
        "people_count": "49",
        "place_count": "25",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:00:25",
        "summary": null,
        "short_name": "Mic"
    },
    {
        "id": 34,
        "book_id": "recQKyO5TMxwPm4Ky",
        "book_number": 34,
        "osis_name": "Nah",
        "label": "Nahum",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "3",
        "verse_count": "47",
        "writers": "[\"nahum_2145\"]",
        "slug": "nah",
        "people_count": "11",
        "place_count": "7",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:34:12",
        "summary": null,
        "short_name": "Na"
    },
    {
        "id": 35,
        "book_id": "rectOGfyQI1dkl9Jy",
        "book_number": 35,
        "osis_name": "Hab",
        "label": "Habakkuk",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "3",
        "verse_count": "56",
        "writers": "[\"habakkuk_1334\"]",
        "slug": "hab",
        "people_count": "15",
        "place_count": "3",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:41:24",
        "summary": null,
        "short_name": "Hab"
    },
    {
        "id": 36,
        "book_id": "recRmQJUpakFullFM",
        "book_number": 36,
        "osis_name": "Zeph",
        "label": "Zephaniah",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "3",
        "verse_count": "53",
        "writers": "[\"zephaniah_3040\"]",
        "slug": "zeph",
        "people_count": "29",
        "place_count": "13",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:42:04",
        "summary": null,
        "short_name": "Zep"
    },
    {
        "id": 37,
        "book_id": "recieu3CSdcWH6rMj",
        "book_number": 37,
        "osis_name": "Hag",
        "label": "Haggai",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "2",
        "verse_count": "38",
        "writers": "[\"haggai_1349\"]",
        "slug": "hag",
        "people_count": "28",
        "place_count": "1",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:42:48",
        "summary": null,
        "short_name": "Hag"
    },
    {
        "id": 38,
        "book_id": "rec2EEptPS7M8gQC3",
        "book_number": 38,
        "osis_name": "Zech",
        "label": "Zechariah",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "14",
        "verse_count": "211",
        "writers": "[\"zechariah_3016\"]",
        "slug": "zech",
        "people_count": "120",
        "place_count": "58",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:43:09",
        "summary": null,
        "short_name": "Zec"
    },
    {
        "id": 39,
        "book_id": "recFNHNgEiPlhRRpQ",
        "book_number": 39,
        "osis_name": "Mal",
        "label": "Malachi",
        "testament": "Old Testament",
        "book_group": "Minor Prophets",
        "chapter_count": "4",
        "verse_count": "55",
        "writers": "[\"malachi_1899\"]",
        "slug": "mal",
        "people_count": "47",
        "place_count": "4",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:45:42",
        "summary": null,
        "short_name": "Mal"
    },
    {
        "id": 40,
        "book_id": "recEJId5B98HV0x6D",
        "book_number": 40,
        "osis_name": "Matt",
        "label": "Matthew",
        "testament": "New Testament",
        "book_group": "Gospels",
        "chapter_count": "28",
        "verse_count": "1071",
        "writers": "[\"matthew_1971\"]",
        "slug": "matt",
        "people_count": "431",
        "place_count": "69",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 05:46:21",
        "summary": null,
        "short_name": "Mt"
    },
    {
        "id": 41,
        "book_id": "recNvq1wZtB13BbbW",
        "book_number": 41,
        "osis_name": "Mark",
        "label": "Mark",
        "testament": "New Testament",
        "book_group": "Gospels",
        "chapter_count": "16",
        "verse_count": "678",
        "writers": "[\"mark_1679\"]",
        "slug": "mark",
        "people_count": "245",
        "place_count": "46",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:10:12",
        "summary": null,
        "short_name": "Mk"
    },
    {
        "id": 42,
        "book_id": "recclIex2hH0wdTST",
        "book_number": 42,
        "osis_name": "Luke",
        "label": "Luke",
        "testament": "New Testament",
        "book_group": "Gospels",
        "chapter_count": "24",
        "verse_count": "1151",
        "writers": "[\"luke_1836\"]",
        "slug": "luke",
        "people_count": "461",
        "place_count": "76",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:17:58",
        "summary": null,
        "short_name": "Lu"
    },
    {
        "id": 43,
        "book_id": "recq8W1kWwtVoUlwB",
        "book_number": 43,
        "osis_name": "John",
        "label": "John",
        "testament": "New Testament",
        "book_group": "Gospels",
        "chapter_count": "21",
        "verse_count": "879",
        "writers": "[\"john_1677\"]",
        "slug": "john",
        "people_count": "514",
        "place_count": "62",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:27:52",
        "summary": null,
        "short_name": "Jn"
    },
    {
        "id": 44,
        "book_id": "recF09FMjRr0gzjQk",
        "book_number": 44,
        "osis_name": "Acts",
        "label": "Acts",
        "testament": "New Testament",
        "book_group": "Acts",
        "chapter_count": "28",
        "verse_count": "1007",
        "writers": "[\"luke_1836\"]",
        "slug": "acts",
        "people_count": "592",
        "place_count": "244",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:35:52",
        "summary": null,
        "short_name": "Ac"
    },
    {
        "id": 45,
        "book_id": "recyvIyxRMFob6SoM",
        "book_number": 45,
        "osis_name": "Rom",
        "label": "Romans",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "16",
        "verse_count": "433",
        "writers": "[\"paul_2479\"]",
        "slug": "rom",
        "people_count": "238",
        "place_count": "13",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:48:45",
        "summary": null,
        "short_name": "Ro"
    },
    {
        "id": 46,
        "book_id": "recVtbTyqtbbtqRC5",
        "book_number": 46,
        "osis_name": "1Cor",
        "label": "1 Corinthians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "16",
        "verse_count": "437",
        "writers": "[\"paul_2479\"]",
        "slug": "1cor",
        "people_count": "192",
        "place_count": "8",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:54:34",
        "summary": null,
        "short_name": "1Co"
    },
    {
        "id": 47,
        "book_id": "rec0CTDRtMnNCmQr9",
        "book_number": 47,
        "osis_name": "2Cor",
        "label": "2 Corinthians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "13",
        "verse_count": "257",
        "writers": "[\"paul_2479\"]",
        "slug": "2cor",
        "people_count": "122",
        "place_count": "12",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 08:58:57",
        "summary": null,
        "short_name": "2Co"
    },
    {
        "id": 48,
        "book_id": "recF3ilKWfSjLzpsj",
        "book_number": 48,
        "osis_name": "Gal",
        "label": "Galatians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "6",
        "verse_count": "149",
        "writers": "[\"paul_2479\"]",
        "slug": "gal",
        "people_count": "87",
        "place_count": "10",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:02:15",
        "summary": null,
        "short_name": "Ga"
    },
    {
        "id": 49,
        "book_id": "rec3IwUp30NnnEqSL",
        "book_number": 49,
        "osis_name": "Eph",
        "label": "Ephesians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "6",
        "verse_count": "155",
        "writers": "[\"paul_2479\"]",
        "slug": "eph",
        "people_count": "88",
        "place_count": "1",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:04:19",
        "summary": null,
        "short_name": "Eph"
    },
    {
        "id": 50,
        "book_id": "recY95JJhNEzOwMNv",
        "book_number": 50,
        "osis_name": "Phil",
        "label": "Philippians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "4",
        "verse_count": "104",
        "writers": "[\"paul_2479\"]",
        "slug": "phil",
        "people_count": "63",
        "place_count": "3",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:06:44",
        "summary": null,
        "short_name": "Php"
    },
    {
        "id": 51,
        "book_id": "recY37UhYyyAlabnd",
        "book_number": 51,
        "osis_name": "Col",
        "label": "Colossians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "4",
        "verse_count": "95",
        "writers": "[\"paul_2479\"]",
        "slug": "col",
        "people_count": "51",
        "place_count": "5",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:08:13",
        "summary": null,
        "short_name": "Col"
    },
    {
        "id": 52,
        "book_id": "recDZc63lmQiSe0gn",
        "book_number": 52,
        "osis_name": "1Thess",
        "label": "1 Thessalonians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "5",
        "verse_count": "89",
        "writers": "[\"paul_2479\"]",
        "slug": "1thess",
        "people_count": "49",
        "place_count": "6",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:09:42",
        "summary": null,
        "short_name": "1Th"
    },
    {
        "id": 53,
        "book_id": "recnZBkoT7W0SV19v",
        "book_number": 53,
        "osis_name": "2Thess",
        "label": "2 Thessalonians",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "3",
        "verse_count": "47",
        "writers": "[\"paul_2479\"]",
        "slug": "2thess",
        "people_count": "29",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:10:59",
        "summary": null,
        "short_name": "2Th"
    },
    {
        "id": 54,
        "book_id": "rec2yyoaHMOHZcynX",
        "book_number": 54,
        "osis_name": "1Tim",
        "label": "1 Timothy",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "6",
        "verse_count": "113",
        "writers": "[\"paul_2479\"]",
        "slug": "1tim",
        "people_count": "38",
        "place_count": "1",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:11:41",
        "summary": null,
        "short_name": "1Ti"
    },
    {
        "id": 55,
        "book_id": "rec28yVZWWOL1gftz",
        "book_number": 55,
        "osis_name": "2Tim",
        "label": "2 Timothy",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "4",
        "verse_count": "83",
        "writers": "[\"paul_2479\"]",
        "slug": "2tim",
        "people_count": "47",
        "place_count": "8",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:13:20",
        "summary": null,
        "short_name": "2Ti"
    },
    {
        "id": 56,
        "book_id": "recZJmtLFS2QnJG2b",
        "book_number": 56,
        "osis_name": "Titus",
        "label": "Titus",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "3",
        "verse_count": "46",
        "writers": "[\"paul_2479\"]",
        "slug": "titus",
        "people_count": "16",
        "place_count": "2",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:14:29",
        "summary": null,
        "short_name": "Tit"
    },
    {
        "id": 57,
        "book_id": "recZm66X4kEQ7X3j2",
        "book_number": 57,
        "osis_name": "Phlm",
        "label": "Philemon",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "1",
        "verse_count": "25",
        "writers": "[\"paul_2479\"]",
        "slug": "phlm",
        "people_count": "15",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:15:18",
        "summary": null,
        "short_name": "Phm"
    },
    {
        "id": 58,
        "book_id": "recKvTNUismk1ckEr",
        "book_number": 58,
        "osis_name": "Heb",
        "label": "Hebrews",
        "testament": "New Testament",
        "book_group": "Pauline Epistles",
        "chapter_count": "13",
        "verse_count": "303",
        "writers": "[\"paul_2479\"]",
        "slug": "heb",
        "people_count": "139",
        "place_count": "11",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:15:30",
        "summary": null,
        "short_name": "Heb"
    },
    {
        "id": 59,
        "book_id": "recDk5A8p9VHMaXAC",
        "book_number": 59,
        "osis_name": "Jas",
        "label": "James",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "5",
        "verse_count": "108",
        "writers": "[\"james_719\"]",
        "slug": "jas",
        "people_count": "29",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:20:10",
        "summary": null,
        "short_name": "Jas"
    },
    {
        "id": 60,
        "book_id": "receVE4rg7HzwRays",
        "book_number": 60,
        "osis_name": "1Pet",
        "label": "1 Peter",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "5",
        "verse_count": "105",
        "writers": "[\"peter_2745\"]",
        "slug": "1pet",
        "people_count": "56",
        "place_count": "3",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:21:39",
        "summary": null,
        "short_name": "1Pe"
    },
    {
        "id": 61,
        "book_id": "recFNtUGO3RQUDGPv",
        "book_number": 61,
        "osis_name": "2Pet",
        "label": "2 Peter",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "3",
        "verse_count": "61",
        "writers": "[\"peter_2745\"]",
        "slug": "2pet",
        "people_count": "24",
        "place_count": "1",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:23:48",
        "summary": null,
        "short_name": "2Pe"
    },
    {
        "id": 62,
        "book_id": "recnCKWpaf0b7Q1dy",
        "book_number": 62,
        "osis_name": "1John",
        "label": "1 John",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "5",
        "verse_count": "105",
        "writers": "[\"john_1677\"]",
        "slug": "1john",
        "people_count": "61",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:24:45",
        "summary": null,
        "short_name": "1Jn"
    },
    {
        "id": 63,
        "book_id": "recvfX2A1wSqR2QiC",
        "book_number": 63,
        "osis_name": "2John",
        "label": "2 John",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "1",
        "verse_count": "13",
        "writers": "[\"john_1677\"]",
        "slug": "2john",
        "people_count": "6",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:26:29",
        "summary": null,
        "short_name": "2Jn"
    },
    {
        "id": 64,
        "book_id": "recMApftYXBHE8lV5",
        "book_number": 64,
        "osis_name": "3John",
        "label": "3 John",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "1",
        "verse_count": "14",
        "writers": "[\"john_1677\"]",
        "slug": "3john",
        "people_count": "4",
        "place_count": "0",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:26:37",
        "summary": null,
        "short_name": "3Jn"
    },
    {
        "id": 65,
        "book_id": "rec2ddtGk1mJxYoy4",
        "book_number": 65,
        "osis_name": "Jude",
        "label": "Jude",
        "testament": "New Testament",
        "book_group": "General Epistles",
        "chapter_count": "1",
        "verse_count": "25",
        "writers": "[\"jude_1756\"]",
        "slug": "jude",
        "people_count": "11",
        "place_count": "2",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:26:46",
        "summary": null,
        "short_name": "Jud"
    },
    {
        "id": 66,
        "book_id": "recUbhyLLUrl849r7",
        "book_number": 66,
        "osis_name": "Rev",
        "label": "Revelation",
        "testament": "New Testament",
        "book_group": "Revelation",
        "chapter_count": "22",
        "verse_count": "404",
        "writers": "[\"john_1677\"]",
        "slug": "rev",
        "people_count": "156",
        "place_count": "27",
        "created_at": "2022-12-11 11:29:12",
        "updated_at": "2022-12-13 09:27:11",
        "summary": null,
        "short_name": "Re"
    }
]